export const LOAD_DASH = 'LOAD_DASH';
export const LOAD_DASH_SUCCESS = 'LOAD_DASH_SUCCESS';
export const LOAD_DASH_ERROR = 'LOAD_DASH_ERROR';

export const SET_MODE = 'SET_MODE';
export const SET_ERROR_MODE = 'SET_ERROR_MODE';
export const CANCEL_EDIT_MODE = 'CANCEL_EDIT_MODE';

export const SAVE_DASH_SUCCESS = 'SAVE_DASH_SUCCESS';
export const SAVE_DASH_ERROR = 'SAVE_DASH_ERROR';

// TODO: SET_PAGE_ACTIVE_TAB
export const SET_PAGE_TAB = 'SET_PAGE_TAB';

export const OPEN_DIALOG = 'OPEN_DIALOG';
export const OPEN_ITEM_DIALOG = 'OPEN_ITEM_DIALOG';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';

export const OPEN_EXPANDED_FILTER = 'OPEN_EXPANDED_FILTER';
export const CLOSE_EXPANDED_FILTER = 'CLOSE_EXPANDED_FILTER';

export const SET_TABS = 'SET_TABS';

export const SET_SETTINGS = 'SET_SETTINGS';

export const SET_ITEM_DATA = 'SET_ITEM_DATA';

export const SET_CURRENT_TAB_DATA = 'SET_CURRENT_TAB_DATA';
export const UPDATE_CURRENT_TAB_DATA = 'UPDATE_CURRENT_TAB_DATA';

export const SET_HASH_STATE = 'SET_HASH_STATE';

export const TOGGLE_TABLE_OF_CONTENT = 'TOGGLE_TABLE_OF_CONTENT';

export const SET_DASHKIT_REF = 'SET_DASHKIT_REF';

export const CHANGE_NAVIGATION_PATH = 'CHANGE_NAVIGATION_PATH';

export const RESET_ALL_FILTERS = 'RESET_ALL_FILTERS';

export const SET_WIDGET_EDITOR_UUID = 'SET_WIDGET_EDITOR_UUID';

export const SET_WIDGET_FOR_RELOAD_UUID = 'SET_WIDGET_FOR_RELOAD_UUID';

export const TOGGLE_WIDGET_VISIBILITY = 'TOGGLE_WIDGET_VISIBILITY';

export const START_EXPORT = 'START_EXPORT';
export const END_EXPORT = 'END_EXPORT';
export const EXPORT_ERROR = 'EXPORT_ERROR';
export const EXPORT_STATUS_RESET = 'EXPORT_STATUS_RESET';
