export const ROUTES = {
  root: '/',
  navigation: '/navigation',
  navigationId: '/navigation/:id',
  favorites: '/favorites',
  favoritesId: '/favorites/:id',
  connections: '/connections',
  connectionsId: '/connections/:id',
  connectionsInFolder: '/connections_in_folder/:id',
  datasets: '/datasets',
  datasetsInFolder: '/datasets_in_folder/:id',
  datasetsId: '/datasets/:id',
  widgets: '/widgets',
  widgetsInFolder: '/widgets_in_folder/:id',
  wizard: '/wizard/:id',
  dashboards: '/dashboards',
  dashboardsInFolder: '/dashboards_in_folder/:id',
  dashboardsId: '/dashboards/:id',
};
